site_name: React Decoupled StarterKit

repo_url: https://github.com/acquia-pso/decoupledkit-react
site_description: 'A starterkit for headless workflows with Drupal, React, & GraphQL'
theme: readthedocs
strict: true

extra_javascript:
  - readme/js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Overview: 'index.md'
  - Getting started: 'docs/gettingstarted.md'
    - Drupal: 'docs/gettingstarted-drupal.md'
    - GraphQL: 'docs/gettingstarted-graphql.md'
    - React: 'docs/gettingstarted-react.md'
  - Drupal Documentation: 'docs/drupal.md'
    - Drupal Content Model: 'docs/drupal-contenttypes.md'
    - Drupal OAuth Settings: 'docs/drupal-oauth.md'
    - Drupal API Consumers: 'docs/drupal-consumer.md'
    - Drupal API Roles: 'docs/drupal-roles.md'
    - Drupal API Tokens: 'docs/drupal-tokens.md'
  - GraphQL Documentation: 'docs/graphql.md'
    - Architecture Overview: 'docs/graphql-architecture.md'
    - Apollo Engine Overview: 'docs/graphql-apollo.md'
    - Node.js Application: 'docs/graphql-nodejs.md'
    - Data Sources: 'docs/graphql-sources.md'
    - Pokemon: 'docs/graphql-pokemon.md'
    - Marvel: 'docs/graphql-marvel.md'
  - React Documentation: 'docs/react.md'
    - Architecture Overview: 'docs/react-architecture.md'
    - Drupal CRUD Operations: 'docs/react-drupalcrud.md'
    - Drupal GraphQL (single): 'docs/react-graphqlsingle.md'
    - Drupal GraphQL (multiple): 'docs/react-graphqlmultiple.md'
    - API Failover Techniques: 'docs/react-apifailover.md'
    - API Mocking Techniques: 'docs/react-apimock.md'

