site_name: React Decoupled StarterKit

repo_url: https://github.com/acquia-pso/decoupledkit-react
site_description: 'A starterkit for headless workflows with Drupal, React, & GraphQL'
theme: readthedocs
strict: true

# extra_javascript:
#   - js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Getting started:
    - Drupal: 'gettingstarted-drupal.md'
    - GraphQL: 'gettingstarted-graphql.md'
    - React: 'gettingstarted-react.md'
  - Drupal Documentation:
    - Drupal Overview: 'drupal.md'
    - Drupal Content Model: 'drupal-contenttypes.md'
    - Drupal OAuth Settings: 'drupal-oauth.md'
    - Drupal API Consumers: 'drupal-consumer.md'
    - Drupal API Roles: 'drupal-roles.md'
    - Drupal API Tokens: 'drupal-tokens.md'
  - GraphQL Documentation:
    - GraphQL Overview: 'graphql.md'
    - Architecture Overview: 'graphql-architecture.md'
    - Apollo Engine Overview: 'graphql-apollo.md'
    - Node.js Application: 'graphql-nodejs.md'
    - Data Sources: 'graphql-sources.md'
    - Pokemon: 'graphql-pokemon.md'
    - Marvel: 'graphql-marvel.md'
  - React Documentation:
    - React Documentation: 'react.md'
    - Architecture Overview: 'react-architecture.md'
    - Drupal CRUD Operations: 'react-drupalcrud.md'
    - Drupal GraphQL (single): 'react-graphqlsingle.md'
    - Drupal GraphQL (multiple): 'react-graphqlmultiple.md'
    - API Failover Techniques: 'react-apifailover.md'
    - API Mocking Techniques: 'react-apimock.md'
